name: Hello Script Every 10 Minutes

on:
  push:
  schedule:
    - cron: "*/5 * * * *"  # cron job to run every 10 minutes
  workflow_dispatch:  

jobs:
  run_hello:
    runs-on: ubuntu-latest # OS to run the job on

    steps: # steps to peform on the OS to run the job
      - name: Checkout code # pulls the code from the repo
        uses: actions/checkout@v4
      - name: Run Hello World script # runs the hello.py script
        run: python hello.py